#!/usr/bin/python 
 
import smtplib 
import base64 
import subprocess

out = subprocess.Popen('ls -lrt *TestReport_*', shell=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE)

stdout,stderr = out.communicate()
print "This is TestReport of Plugin:",(stdout.split()[8])
 
filename = (stdout.split()[8]) 

fo = open(filename, "rb")
filecontent = fo.read()
encodedcontent = base64.b64encode(filecontent)  # base64
marker = "AUNIQUEMARKER"
var="TEST_REPORT:"+filename
body ="""
Hi All, \n \nPlease find attached TEST REPORT of certain plugin. \n \nThis Email is Autogenerated,Do not Reply to this!!!.
"""
# Define the main headers.
part1 = """Subject: %s 
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary=%s
--%s
""" % (var,marker, marker)

# Define the message action
part2 = """Content-Type: text/plain
Content-Transfer-Encoding:8bit

%s
--%s
""" % (body,marker)

# Define the attachment section
part3 = """Content-Type: multipart/mixed; name=\"%s\"
Content-Transfer-Encoding:base64
Content-Disposition: attachment; filename=%s

%s
--%s--
""" %(filename, filename, encodedcontent, marker)

 

sender = 'netx@h3g-qa.com' 
reciever = ['Sanbit.Roy@mycom-osi.com', 'Rajat.Chaubey@mycom-osi.com']
#reciever = "Sanbit.Roy@mycom-osi.com, Rajat.Chaubey@mycom-osi.com"
message = part1 +part2 + part3 
 
try: 
   smtpObj = smtplib.SMTP('localhost')
   smtpObj.sendmail(sender, reciever, message) 
   print "Successfully sent email" 
except Exception: 
   print "Error: unable to send email" 

