#!/usr/bin/python
for j in range(2,21):
 flag=1
 for i in range(2,j):  
       if  not (j%i):  
           print j,"-->NOT PRIME"  
           flag=0
           break  
 if (flag==1):print j,"-->PRIME"
         
